# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quizz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '4.9'
  pod 'AlamofireObjectMapper', '5.2'
  pod 'SDWebImage'
  pod 'RMMapper'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyJSON'
  pod 'Toast-Swift'
  pod 'NVActivityIndicatorView'
  # Pods for Quizz

  target 'QuizzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuizzUITests' do
    # Pods for testing
  end

end
